CREATE SCHEMA pocopay AUTHORIZATION pocopay;

GRANT USAGE ON SCHEMA pocopay TO pocopay;
ALTER DEFAULT PRIVILEGES FOR USER pocopay IN SCHEMA pocopay GRANT USAGE ON SEQUENCES TO pocopay;
ALTER DEFAULT PRIVILEGES FOR USER pocopay IN SCHEMA pocopay GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO pocopay;

