# Use the official OpenJDK 17 image as the base image
FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Expose the port used by your application (if necessary)
EXPOSE 8080

# Start the Spring Boot application when the container launches
CMD ["java", "-jar", "/app/pocopay-home-assignment-0.0.1-SNAPSHOT.jar"]
